services:
  influx:
    image: influxdb:2.5.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: abstracta
      DOCKER_INFLUXDB_INIT_BUCKET: selenium
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
  grafana:
    image: grafana/grafana:8.2.6
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 1234
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/dashboard.json
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/:/etc/grafana/provisioning
volumes:
  influx-data:
  influx-config:
  grafana-data: