{
 "title": "UX & Backend Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Step Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"upper\")\n  |> group(columns: [\"_measurement\", \"session\"])\n  |> last()\n  |> group(columns: [\"_measurement\"])\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Times per Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"jmeter\" and r._field == \"pct99.0\" and r.statut == \"ok\")\n  |> keep(columns: [\"_time\", \"_value\", \"transaction\"])"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "  from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\" and r[\"_field\"] == \"maxAT\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "Requests Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"jmeter\" and r.transaction == \"all\" and (r._field == \"count\" or r._field == \"countError\"))\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  "
    }
   ]
  },
  {
   "title": "Errors Count per Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"jmeter\" and r.statut == \"ko\" and r._field == \"count\")\n  |> keep(columns: [\"_time\", \"transaction\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"selenium\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"jmeter\" and r.responseMessage != \"\")\n  |> group(columns: [\"responseMessage\"])\n  |> keep(columns: [\"_time\", \"responseMessage\", \"_value\"])\n  |> aggregateWindow(every: 1s, fn: sum)"
    }
   ]
  }
 ]
}